version: '3'
services:
    web:
        container_name: nginx
        image: nginx:latest
        ports:
            - '8000:80'
        volumes:
            #- /Users/mathewthompson/Documents/dev/web:/var/www/html
            - ./web:/var/www/html
            - "./site.conf:/etc/nginx/conf.d/default.conf"
        links:
            - php
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"

    php:
        build: .
        container_name: php
        image: php:7.2-fpm
        volumes:
            #- /Users/mathewthompson/Documents/dev/web:/var/www/html
            - ./web:/var/www/html

    db:
        # build:
        #     context: ./
        #     dockerfile: Dockerfile.mysql
        container_name: mysql
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
            - ./init-table.sql:/docker-entrypoint-initdb.d/init-table.sql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: products
            MYSQL_USER: products
            MYSQL_PASSWORD: products

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db_data: